version: '3.8'
services:
  test-db:
    image: postgres:16
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nhanbui
      POSTGRES_DB: hongheovna
    networks:
      - vnainternship
networks:
  vnainternship: